name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # This fixes the fact that docker-as-root creates this dir, locking us from copying the CSS to it
      - name: Create the build directory
        run: mkdir -vp build

      - name: Build
        uses: cheeplusplus/simplestaticsitegen@0.0.9-gha 
        with:
          source: src
          target: build
          filesAsDirs: true
          ignore: "*.json,*.scss"
      
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.2.1
        with:
          source: src/site.scss
          destination: build/site.css

      - name: S3 Sync
        if: success() && github.ref == 'refs/heads/master'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'build'
